# The recording directories of this archive.
#
# The audio files of the recordings of an archive are stored in
# *recording directories*, whose paths are specified by this setting.
# An archive typically has a single recording directory, though multiple
# recording directories are also supported.
#
# The value of this setting is a list of recording directory paths.
# Each path can be either absolute or relative. If it is relative, it
# it must be relative to the archive directory. If the setting is
# omitted, it defaults to the "Recordings" subdirectory of the archive
# directory.
#
# The path of each recording audio file of an archive is stored in the
# archive database as a relative path, or more specifically a path that
# is relative to the recording directory that contains the file. In
# order to access a file, Vesper must first locate the file in one of
# the recording directories. It does this by searching for the file in
# the recording directories in the order specified by this setting.
# Note that for this to work, the relative paths of the recording audio
# files stored in the archive database must be unique. This is good
# practice anyway: commonly, for example, the audio file names
# themselves are unique, with each including a unique station name and
# the file's start time.
# recording_directories:
#     - 'W:\NFC\Recordings'           # Windows
#     - '/Volumes/NFC/Recordings'     # macOS
